{
    profilesCollection(
        ARG,
    ) {
        edges {
            node {
                id
                name
                surname
                profile_pic
                lang
                country
            }
        }
    }
}