# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: LaNotte24Ore CI/CD Development

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      IPINFO_API_KEY: ${{ secrets.IPINFO_API_KEY }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      DATABASE_KEY: ${{ secrets.DATABASE_KEY }}
      AUTH_TEST_USER: ${{ secrets.AUTH_TEST_USER }}
      AUTH_TEST_PASSWORD: ${{ secrets.AUTH_TEST_PASSWORD }}
      

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - name: Install Python and Node dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        npm install --save
    - name: Compile CSS
      run: |
        npm run build:dev
    - name: Endpoints test
      run: |
        python -m pytest -v